Repository WalletConnect/walletconnect-monorepo, pull requests merged in 2022-11, with the labels that each got.

#1577 fix(types): removes leftover `pairing_` references in client types
  packages/types/src/sign-client/client.ts
Labels: accepted

#1585 feat(o11y): integrate with statuspage
  packages/sign-client/test/canary/canary.spec.ts
  packages/sign-client/test/shared/index.ts
  packages/sign-client/test/shared/status.ts
Labels: accepted

#1590 fix: socket transport manual start/stop
  packages/core/src/controllers/relayer.ts
  packages/core/src/controllers/subscriber.ts
  packages/sign-client/test/sdk/client.spec.ts
Labels: type: bug, type: enhancement, accepted

#1591 feat: connect & disconnect fx types
  providers/universal-provider/src/types/providers.ts
Labels: accepted

#1593 chore: v2.1.1
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package-lock.json
  providers/universal-provider/package.json
Labels: accepted

#1598 fix: universal provider persistance
  .github/workflows/pr_checks.yml
  providers/universal-provider/src/UniversalProvider.ts
  providers/universal-provider/src/types/misc.ts
  providers/universal-provider/test/index.spec.ts
  providers/universal-provider/test/shared/connect.ts
  providers/universal-provider/test/shared/constants.ts
  providers/universal-provider/test/shared/helpers.ts
  providers/universal-provider/test/shared/index.ts
  providers/universal-provider/test/shared/ws.ts
Labels: type: bug, type: enhancement, accepted

#1599 feat(test): cover reconnection lifecycle
  packages/sign-client/package.json
  packages/sign-client/test/lifecycle/lifecycle.spec.ts
Labels: accepted

#1616 chore: logger update
  package-lock.json
  package.json
  packages/core/package.json
  packages/core/src/controllers/crypto.ts
  packages/core/src/controllers/expirer.ts
  packages/core/src/controllers/history.ts
  packages/core/src/controllers/keychain.ts
  packages/core/src/controllers/messages.ts
  packages/core/src/controllers/pairing.ts
  packages/core/src/controllers/publisher.ts
  packages/core/src/controllers/relayer.ts
  packages/core/src/controllers/store.ts
  packages/core/src/controllers/subscriber.ts
  packages/core/src/core.ts
  packages/core/test/crypto.spec.ts
  packages/core/test/keychain.spec.ts
  packages/core/test/messages.spec.ts
  packages/core/test/relayer.spec.ts
  packages/core/test/store.spec.ts
  packages/core/test/subscriber.spec.ts
  packages/sign-client/package.json
  packages/sign-client/src/client.ts
  packages/sign-client/src/controllers/proposal.ts
  packages/sign-client/src/controllers/session.ts
  packages/types/package.json
  packages/types/src/core/core.ts
  packages/types/src/core/crypto.ts
  packages/types/src/core/expirer.ts
  packages/types/src/core/history.ts
  packages/types/src/core/keychain.ts
  packages/types/src/core/messages.ts
  packages/types/src/core/pairing.ts
  packages/types/src/core/publisher.ts
  packages/types/src/core/relayer.ts
  packages/types/src/core/store.ts
  packages/types/src/core/subscriber.ts
  packages/types/src/sign-client/client.ts
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package-lock.json
  providers/universal-provider/package.json
  providers/universal-provider/src/UniversalProvider.ts
Labels: type: enhancement, accepted

#1626 chore: v2.1.2
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#1627 fix: x region tests transport disconnnect
  packages/sign-client/test/lifecycle/lifecycle.spec.ts
  packages/sign-client/test/xregion/xregion.spec.ts
Labels: type: bug, type: enhancement, accepted

#1635 fix(deps): ensure pino import resolves at runtime
  package-lock.json
  packages/core/package.json
  packages/core/src/controllers/relayer.ts
  packages/core/src/core.ts
  packages/sign-client/package.json
  packages/sign-client/src/client.ts
  providers/universal-provider/package.json
  providers/universal-provider/src/UniversalProvider.ts
Labels: accepted

#1643 fix: resubscribing after transport is reopened
  packages/core/src/constants/subscriber.ts
  packages/core/src/controllers/relayer.ts
  packages/core/src/controllers/subscriber.ts
Labels: accepted

#1669 chore(deps): update jsonrpc-ws-connection to fix various WS issues
  package-lock.json
  packages/core/package.json
  packages/sign-client/package.json
Labels: accepted

#1682 fix: tests reliability
  packages/core/test/shared/ws.ts
  packages/sign-client/package.json
  packages/sign-client/src/controllers/engine.ts
  packages/sign-client/test/sdk/validation.spec.ts
  packages/sign-client/test/shared/values.ts
  packages/sign-client/test/shared/ws.ts
Labels: type: enhancement, accepted
