Repository WalletConnect/walletconnect-monorepo, pull requests merged in 2022-09, with the labels that each got.

#1408 fix(engine): avoids race condition when deleting pairing/session
  packages/sign-client/src/controllers/engine.ts
Labels: accepted

#1411 fix(engine): ensure requesting client sets own record pre `sendRequest`
  packages/sign-client/src/controllers/engine.ts
Labels: accepted

#1412 fix(tests): ensures expected test env vars are passed to Relayer
  packages/core/test/publisher.spec.ts
  packages/core/test/relayer.spec.ts
  packages/core/test/subscriber.spec.ts
Labels: accepted

#1417 feat: print client ids
  packages/sign-client/test/canary/canary.spec.ts
Labels: accepted

#1400 feat(canary): log client id
  packages/sign-client/test/canary/canary.spec.ts
Labels: accepted

#1423 feat(canary): depict region
  packages/sign-client/test/canary/canary.spec.ts
  packages/sign-client/test/shared/metrics.ts
Labels: accepted

#1433 Set build target to ES2020
  tsconfig.json
Labels: accepted

#1424 fix(engine): ensure proposal/session expiry is calculated dynamically
  packages/sign-client/src/constants/proposal.ts
  packages/sign-client/src/constants/session.ts
  packages/sign-client/src/controllers/engine.ts
  packages/sign-client/test/sdk/client.spec.ts
  packages/sign-client/test/shared/connect.ts
Labels: accepted

#1435 2.0.0-rc.3
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/react-native-compat/package.json
  packages/sign-client/package-lock.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
Labels: accepted

#1426 feat: don't export metrics in dev
  packages/sign-client/test/canary/canary.spec.ts
Labels: accepted

#1442 feat: introduce qr code scan time
  packages/sign-client/test/canary/canary.spec.ts
  packages/sign-client/test/shared/connect.ts
Labels: accepted

#1444 feat(canary): granular latency metrics
  packages/sign-client/test/canary/canary.spec.ts
  packages/sign-client/test/shared/connect.ts
  packages/sign-client/test/shared/metrics.ts
Labels: accepted

#1446 feat(canary): cover session_ping
  packages/sign-client/test/canary/canary.spec.ts
Labels: accepted

#1448 feat(test): extend some timeouts
  packages/sign-client/test/sdk/client.spec.ts
Labels: accepted

#1449 test: adds `test:ignoreUnhandled` script to unblock rs-relay pipeline
  package.json
  packages/core/package.json
  packages/sign-client/package.json
  packages/utils/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
Labels: accepted

#1453 feat(canary): timeout connect
  packages/sign-client/test/shared/connect.ts
Labels: accepted

#1455 feat: log client ids when tests fail
  packages/sign-client/test/sdk/client.spec.ts
Labels: accepted

#1456 feat: log client id when pairing fails
  packages/sign-client/test/sdk/client.spec.ts
Labels: accepted

#1457 feat: timeout pair()
  packages/sign-client/test/sdk/client.spec.ts
  packages/sign-client/test/shared/connect.ts
  vitest.config.ts
Labels: accepted

#1458 feat: log client ids when restart tests fail
  packages/sign-client/test/sdk/client.spec.ts
Labels: accepted

#1459 fix(engine): avoids unwanted expirer deletion attempts post-expiry
  packages/sign-client/src/controllers/engine.ts
  packages/types/src/sign-client/engine.ts
Labels: accepted

#1462 fix(test): ensure generated persistent DBs are always unique
  .gitignore
  packages/sign-client/package.json
  packages/sign-client/test/sdk/client.spec.ts
Labels: accepted

#1464 feat(test): log client ids
  packages/sign-client/test/sdk/events.spec.ts
Labels: accepted

#1466 chore(test): log client ids proper when tests fail
  packages/sign-client/test/sdk/events.spec.ts
  packages/sign-client/test/sdk/push.spec.ts
Labels: accepted

#1467 Revert "Merge pull request #1461 from WalletConnect/chore/storage-update"
  package-lock.json
  packages/core/package.json
  packages/sign-client/package.json
Labels: accepted

#1468 fix(test): push test fails occasionally
  packages/sign-client/test/sdk/push.spec.ts
Labels: accepted

#1470 chore(test): disable flaking persistent storage test temporarily
  packages/sign-client/test/sdk/client.spec.ts
Labels: accepted

#1469 chore(test): debug output when restart tests fail
  packages/sign-client/test/sdk/client.spec.ts
Labels: accepted

#1478 chore: sets up `core/pairing` skeleton
  packages/core/src/constants/index.ts
  packages/core/src/constants/pairing.ts
  packages/core/src/controllers/pairing.ts
  packages/types/src/core/index.ts
  packages/types/src/core/pairing.ts
  packages/types/src/sign-client/client.ts
  packages/types/src/sign-client/engine.ts
  packages/types/src/sign-client/index.ts
  packages/types/src/sign-client/pairing.ts
Labels: accepted

#1473 chore: re storage update
  package-lock.json
  packages/core/package.json
  packages/core/src/controllers/relayer.ts
  packages/core/test/publisher.spec.ts
  packages/core/test/relayer.spec.ts
  packages/core/test/shared/helpers.ts
  packages/core/test/shared/index.ts
  packages/core/test/shared/ws.ts
  packages/core/test/subscriber.spec.ts
  packages/sign-client/package.json
  packages/sign-client/test/sdk/client.spec.ts
  packages/sign-client/test/shared/helpers.ts
  packages/sign-client/test/shared/index.ts
  packages/sign-client/test/shared/ws.ts
  vitest.config.ts
Labels: accepted

#1483 Fix/restart test
  packages/sign-client/test/sdk/client.spec.ts
Labels: accepted

#1484 fix: pings race condition
  packages/sign-client/src/controllers/engine.ts
Labels: type: bug, priority: high, accepted

#1485 feat: implement first iteration of core/pairing
  packages/core/src/constants/history.ts
  packages/core/src/constants/index.ts
  packages/core/src/constants/pairing.ts
  packages/core/src/controllers/history.ts
  packages/core/src/controllers/index.ts
  packages/core/src/controllers/pairing.ts
  packages/core/src/core.ts
  packages/core/test/pairing.spec.ts
  packages/types/src/core/core.ts
  packages/types/src/core/pairing.ts
Labels: accepted

#1487 fix: sockets remain open after test completion
  packages/core/test/publisher.spec.ts
  packages/core/test/relayer.spec.ts
  packages/core/test/shared/ws.ts
  packages/core/test/subscriber.spec.ts
  packages/sign-client/test/sdk/client.spec.ts
  packages/sign-client/test/sdk/events.spec.ts
  packages/sign-client/test/shared/helpers.ts
  packages/sign-client/test/shared/init.ts
  packages/sign-client/test/shared/ws.ts
Labels: type: bug, type: enhancement, accepted
