Repository WalletConnect/walletconnect-monorepo, pull requests merged in 2022-10, with the labels that each got.

#1502 feat: reenable TTL
  packages/sign-client/src/constants/engine.ts
Labels: type: enhancement, accepted

#1504 feat(test): cover pairing/ping in xregion test
  packages/sign-client/test/xregion/xregion.spec.ts
Labels: accepted

#1506 feat: implements first pass of pairing API sign integration
  packages/core/src/constants/pairing.ts
  packages/core/src/controllers/pairing.ts
  packages/core/src/core.ts
  packages/sign-client/src/client.ts
  packages/sign-client/src/controllers/engine.ts
  packages/sign-client/src/controllers/history.ts
  packages/sign-client/src/controllers/index.ts
  packages/sign-client/src/controllers/pairing.ts
  packages/sign-client/test/sdk/client.spec.ts
  packages/types/src/core/core.ts
  packages/types/src/core/pairing.ts
  packages/types/src/sign-client/client.ts
Labels: accepted

#1494 chore: socket hang up investigation
  packages/core/src/controllers/relayer.ts
  packages/core/src/core.ts
  packages/sign-client/src/controllers/engine.ts
  packages/sign-client/test/sdk/client.spec.ts
  packages/sign-client/test/sdk/validation.spec.ts
  packages/sign-client/test/shared/init.ts
Labels: accepted

#1512 2.0.0-rc.4
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/react-native-compat/package.json
  packages/sign-client/package-lock.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
Labels: accepted

#1515 fix: speed up validation tests
  packages/sign-client/test/sdk/validation.spec.ts
Labels: type: enhancement, accepted

#1516 chore: a comment to explain why await is ommited
  packages/sign-client/src/controllers/engine.ts
Labels: accepted

#1517 chore: adds universal-provider to workspaces
  package-lock.json
  package.json
  providers/universal-provider/package.json
  providers/universal-provider/src/types/misc.ts
Labels: accepted

#1518 test(pairing): adjusts test setup/teardown to be websocket-safe
  packages/core/test/pairing.spec.ts
Labels: accepted

#1523 fix(core): fixes missing `isInitialized` check on `store.getAll`
  packages/core/src/controllers/store.ts
Labels: type: bug, protocol-version: v2, accepted

#1524 fix: universal provider required test params
  providers/universal-provider/test/shared/constants.ts
Labels: type: enhancement, accepted

#1525 refactor: moves `expirer` into core, use as singleton
  packages/core/src/constants/expirer.ts
  packages/core/src/constants/index.ts
  packages/core/src/controllers/expirer.ts
  packages/core/src/controllers/index.ts
  packages/core/src/controllers/pairing.ts
  packages/core/src/core.ts
  packages/sign-client/src/client.ts
  packages/sign-client/src/constants/index.ts
  packages/sign-client/src/controllers/engine.ts
  packages/sign-client/src/controllers/index.ts
  packages/types/src/core/core.ts
  packages/types/src/core/expirer.ts
  packages/types/src/core/index.ts
  packages/types/src/sign-client/client.ts
  packages/types/src/sign-client/index.ts
Labels: accepted

#1531 fix: ignoring messages handled by external SDKs
  packages/core/src/controllers/crypto.ts
  packages/core/src/controllers/pairing.ts
  packages/types/src/core/crypto.ts
Labels: type: bug, type: enhancement, accepted

#1535 fix(deps): fixes stale keyvaluestorage storage due to types deps
  package-lock.json
  packages/types/package.json
Labels: accepted

#1536 feat: Pairing API
  packages/core/src/constants/expirer.ts
  packages/core/src/constants/history.ts
  packages/core/src/constants/index.ts
  packages/core/src/constants/pairing.ts
  packages/core/src/controllers/crypto.ts
  packages/core/src/controllers/expirer.ts
  packages/core/src/controllers/history.ts
  packages/core/src/controllers/index.ts
  packages/core/src/controllers/pairing.ts
  packages/core/src/core.ts
  packages/core/test/pairing.spec.ts
  packages/sign-client/package-lock.json
  packages/sign-client/src/client.ts
  packages/sign-client/src/constants/client.ts
  packages/sign-client/src/constants/engine.ts
  packages/sign-client/src/constants/index.ts
  packages/sign-client/src/constants/pairing.ts
  packages/sign-client/src/controllers/engine.ts
  packages/sign-client/src/controllers/index.ts
  packages/sign-client/src/controllers/pairing.ts
  packages/sign-client/test/sdk/client.spec.ts
  packages/sign-client/test/sdk/validation.spec.ts
  packages/types/src/core/core.ts
  packages/types/src/core/crypto.ts
  packages/types/src/core/expirer.ts
  packages/types/src/core/index.ts
  packages/types/src/core/pairing.ts
  packages/types/src/sign-client/client.ts
  packages/types/src/sign-client/engine.ts
  packages/types/src/sign-client/index.ts
  packages/types/src/sign-client/jsonrpc.ts
  packages/types/src/sign-client/pairing.ts
  packages/utils/src/errors.ts
Labels: accepted

#1540 feat: transport lifecycle
  packages/core/src/controllers/relayer.ts
  packages/core/src/controllers/subscriber.ts
  packages/types/src/core/relayer.ts
Labels: type: enhancement, accepted

#1544 chore: 2.1.0
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package-lock.json
  providers/universal-provider/package.json
Labels: accepted
