Repository WalletConnect/walletconnect-monorepo, pull requests merged in 2022-08, with the labels that each got.

#1285 feat: automates intake process
  .github/workflows/intake.yml
Labels: accepted

#1303 chore(deps): updates jsonrpc-ws/http-connection to 1.0.3
  package-lock.json
  packages/core/package.json
  packages/sign-client/package.json
  providers/ethereum-provider/package.json
Labels: accepted

#1309 refactor: canary test timeout
  packages/sign-client/test/canary/canary.spec.ts
Labels: type: enhancement, accepted

#1304 refactor: irn update
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/core/test/publisher.spec.ts
  packages/core/test/subscriber.spec.ts
  packages/sign-client/package.json
  packages/sign-client/src/controllers/engine.ts
  packages/sign-client/test/shared/values.ts
  packages/utils/package.json
  packages/utils/src/relay.ts
  packages/utils/test/shared/values.ts
Labels: type: enhancement, accepted

#1314 feat: add PR template
  .github/pull_request_template.md
Labels: accepted

#1328 fix: intake process only works for public org membership
  .github/workflows/intake.yml
Labels: accepted

#1332 feat: covers push functionality
  packages/sign-client/test/sdk/push.spec.ts
  packages/sign-client/test/shared/values.ts
Labels: accepted

#1347 fix(deps): use exact walletconnect dep version when updating
  package.json
Labels: accepted

#1348 V2.0.0 rc.2
  lerna.json
  package-lock.json
  package.json
  packages/core/package.json
  packages/react-native-compat/.npmignore
  packages/react-native-compat/LICENSE
  packages/react-native-compat/README.md
  packages/react-native-compat/index.js
  packages/react-native-compat/package.json
  packages/sign-client/package-lock.json
  packages/sign-client/package.json
  packages/sign-client/test/sdk/push.spec.ts
  packages/sign-client/test/shared/values.ts
  packages/types/package.json
  packages/utils/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  rollup.config.js
Labels: accepted

#1378 feat: distinguish canary target in metrics
  packages/sign-client/test/canary/canary.spec.ts
  packages/sign-client/test/shared/metrics.ts
Labels: accepted

#1380 chore: allot 10s to tests
  packages/sign-client/test/sdk/client.spec.ts
  vitest.config.ts
Labels: accepted

#1381 chore: logs relay url
  packages/sign-client/test/canary/canary.spec.ts
Labels: accepted

#1382 chore: increase canary timeout
  packages/sign-client/test/canary/canary.spec.ts
Labels: accepted

#1388 feat: connect in batches
  packages/sign-client/test/concurrency/concurrency.spec.ts
  packages/sign-client/test/shared/connect.ts
Labels: accepted

#1383 chore: less noise in load test
  packages/sign-client/test/concurrency/concurrency.spec.ts
  packages/sign-client/test/sdk/client.spec.ts
Labels: accepted

#1384 chore: log topics
  packages/sign-client/test/canary/canary.spec.ts
Labels: accepted

#1391 feat: extend more time to connect
  packages/sign-client/test/concurrency/concurrency.spec.ts
Labels: accepted

#1350 feat: universal provider
  providers/universal-provider/.npmignore
  providers/universal-provider/LICENSE
  providers/universal-provider/README.md
  providers/universal-provider/package-lock.json
  providers/universal-provider/package.json
  providers/universal-provider/rollup.config.js
  providers/universal-provider/src/UniversalProvider.ts
  providers/universal-provider/src/constants/index.ts
  providers/universal-provider/src/constants/values.ts
  providers/universal-provider/src/index.ts
  providers/universal-provider/src/providers/eip155.ts
  providers/universal-provider/src/providers/index.ts
  providers/universal-provider/src/types/index.ts
  providers/universal-provider/src/types/misc.ts
  providers/universal-provider/src/types/providers.ts
  providers/universal-provider/src/utils/index.ts
  providers/universal-provider/src/utils/misc.ts
  providers/universal-provider/test/index.spec.ts
  providers/universal-provider/test/shared/WalletClient.ts
  providers/universal-provider/test/shared/constants.ts
  providers/universal-provider/test/shared/index.ts
  providers/universal-provider/tsconfig.json
Labels: accepted, epic

#1393 fix: not filtering out unsuccessful values
  packages/sign-client/test/concurrency/concurrency.spec.ts
Labels: accepted

#1398 chore: improve syntax
  packages/sign-client/test/concurrency/concurrency.spec.ts
Labels: accepted

#1397 fix(test): fixes separate clients using same persistent DB
  .gitignore
  packages/sign-client/package.json
  packages/sign-client/test/concurrency/concurrency.spec.ts
  packages/sign-client/test/sdk/client.spec.ts
  packages/sign-client/test/shared/init.ts
Labels: accepted

#1399 chore: log runtime
  packages/sign-client/test/canary/canary.spec.ts
Labels: accepted

#1404 fix(test): avoids race condition when binding `session_proposal` listener
  packages/sign-client/test/sdk/client.spec.ts
  packages/sign-client/test/shared/connect.ts
Labels: accepted
