Repository WalletConnect/walletconnect-monorepo, pull requests merged in 2023-08, with the labels that each got.

#3330 chore: prep for `2.9.2` release
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/web3wallet/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#3341 fix: compares `metadata.url` origin to verify attestation origin
  packages/sign-client/src/controllers/engine.ts
Labels: accepted

#3349 fix: verify api queue
  packages/core/src/controllers/verify.ts
  packages/sign-client/src/controllers/engine.ts
Labels: accepted

#3111 feat: user action feedback
  package-lock.json
  packages/core/src/constants/relayer.ts
  packages/core/src/controllers/publisher.ts
  packages/core/src/controllers/relayer.ts
  packages/core/src/controllers/subscriber.ts
  packages/react-native-compat/index.js
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/sign-client/src/controllers/engine.ts
  packages/sign-client/test/sdk/client.spec.ts
  packages/types/src/core/publisher.ts
  packages/types/src/core/relayer.ts
  packages/types/src/sign-client/engine.ts
  packages/utils/src/index.ts
  packages/utils/src/network.ts
  providers/universal-provider/test/index.spec.ts
Labels: accepted

#3410 feat: verify fallback
  packages/core/src/constants/verify.ts
  packages/core/src/controllers/verify.ts
  packages/sign-client/src/controllers/engine.ts
Labels: accepted

#3453 fix: handling multiple requests from mailbox
  packages/sign-client/src/constants/engine.ts
  packages/sign-client/src/controllers/engine.ts
  packages/sign-client/test/sdk/persistence.spec.ts
  packages/types/src/sign-client/engine.ts
Labels: type: bug, type: enhancement, accepted

#3463 fix: undefined accountsChanged emitted after connection
  providers/ethereum-provider/src/EthereumProvider.ts
  providers/ethereum-provider/test/index.spec.ts
Labels: type: bug, accepted

#3472 Add validate with swift yml
  .github/workflows/validate_swift.yml
Labels: accepted

#3481 refactor: request queue
  packages/sign-client/src/controllers/engine.ts
  packages/utils/src/index.ts
  packages/utils/src/memoryStore.ts
  providers/universal-provider/src/UniversalProvider.ts
  providers/universal-provider/src/utils/misc.ts
Labels: accepted

#3471 chore: prep for `2.10.0` release
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/web3wallet/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#3564 refactor: adds `eth_sendTransaction` & `personal_sign` to default opt…
  providers/ethereum-provider/src/EthereumProvider.ts
  providers/ethereum-provider/src/constants/rpc.ts
  providers/ethereum-provider/test/index.spec.ts
  providers/universal-provider/test/index.spec.ts
Labels: accepted

#3569 fix: default rpc provider url
  providers/universal-provider/src/constants/values.ts
  providers/universal-provider/src/providers/cardano.ts
  providers/universal-provider/src/providers/cosmos.ts
  providers/universal-provider/src/providers/eip155.ts
  providers/universal-provider/src/providers/elrond.ts
  providers/universal-provider/src/providers/multiversx.ts
  providers/universal-provider/src/providers/polkadot.ts
  providers/universal-provider/src/providers/solana.ts
  providers/universal-provider/src/utils/misc.ts
  providers/universal-provider/test/index.spec.ts
Labels: type: bug, type: enhancement, accepted
