Repository WalletConnect/walletconnect-monorepo, pull requests merged in 2023-05, with the labels that each got.

#2305 fix: rejected verify iframe
  packages/core/src/controllers/verify.ts
Labels: accepted

#2314 chore: prep for `2.7.3` release
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/web3wallet/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#2327 feat: duplicate pairings cleanup
  packages/sign-client/src/controllers/engine.ts
  packages/sign-client/test/sdk/client.spec.ts
  packages/types/src/sign-client/engine.ts
Labels: type: enhancement

#2385 refactor: linking on react-native
  packages/react-native-compat/index.js
  packages/sign-client/test/sdk/client.spec.ts
  providers/universal-provider/src/utils/deepLinks.ts
Labels: accepted

#2386 chore: prep for `2.7.4` release
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/web3wallet/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#2387 chore(config): sets up "release" PR template and expands standard one
  .github/pr_template_release.md
  .github/pr_template_standard.md
  .github/pull_request_template.md
  .github/pull_request_template.yml
Labels: accepted

#2395 fix: session approval race condition
  packages/core/src/controllers/pairing.ts
  packages/sign-client/src/controllers/engine.ts
  packages/sign-client/test/sdk/client.spec.ts
Labels: type: bug, accepted

#2403 Fix deeplinks generating triple slashes ///
  providers/universal-provider/src/utils/deepLinks.ts
Labels: accepted

#2404 refactor: session ack check
  packages/sign-client/test/shared/connect.ts
Labels: accepted

#2408 chore: 2.7.5 release
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/web3wallet/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#2441 fix: parse pairing topic
  packages/utils/src/uri.ts
  packages/utils/test/uri.spec.ts
Labels: accepted

#2353 refactor: publisher queue
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/core/src/controllers/publisher.ts
  packages/core/src/controllers/relayer.ts
  packages/core/test/publisher.spec.ts
  packages/sign-client/package.json
  packages/sign-client/test/sdk/client.spec.ts
  packages/types/package.json
  packages/types/src/core/relayer.ts
  packages/utils/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#2421 feat: disable provider test ping
  package-lock.json
  providers/ethereum-provider/package.json
  providers/ethereum-provider/src/EthereumProvider.ts
  providers/ethereum-provider/test/index.spec.ts
  providers/universal-provider/package.json
  providers/universal-provider/src/UniversalProvider.ts
  providers/universal-provider/src/providers/cardano.ts
  providers/universal-provider/src/providers/cosmos.ts
  providers/universal-provider/src/providers/eip155.ts
  providers/universal-provider/src/providers/elrond.ts
  providers/universal-provider/src/providers/multiversx.ts
  providers/universal-provider/src/providers/polkadot.ts
  providers/universal-provider/src/providers/solana.ts
  providers/universal-provider/src/types/misc.ts
  providers/universal-provider/src/utils/globals.ts
  providers/universal-provider/src/utils/index.ts
  providers/universal-provider/test/index.spec.ts
  providers/universal-provider/test/shared/constants.ts
Labels: accepted

#2445 chore: prep for `2.7.6` release
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/web3wallet/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#2458 feat: metadata redirect
  packages/sign-client/test/sdk/client.spec.ts
  packages/sign-client/test/shared/values.ts
  packages/types/src/core/core.ts
  packages/web3wallet/test/auth.spec.ts
  packages/web3wallet/test/sign.spec.ts
Labels: accepted

#2464 chore: prep for `2.7.7` release
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/web3wallet/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#2478 fix: duplicate pairings clean up
  packages/sign-client/src/controllers/engine.ts
  packages/sign-client/test/sdk/client.spec.ts
  packages/sign-client/test/shared/values.ts
Labels: type: bug

#2508 feat(Canary): more logs around Cloudwatch
  packages/sign-client/test/shared/metrics.ts
  packages/sign-client/test/shared/status.ts
Labels: accepted
