Repository WalletConnect/walletconnect-monorepo, pull requests merged in 2023-03, with the labels that each got.

#2056 fix: namespace validation
  packages/sign-client/src/controllers/engine.ts
  packages/sign-client/test/sdk/client.spec.ts
  packages/sign-client/test/sdk/validation.spec.ts
  packages/sign-client/test/shared/values.ts
  packages/utils/src/validators.ts
  packages/utils/test/validators.spec.ts
Labels: type: bug, type: enhancement, accepted

#2062 Chore/ethereum provider exports
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#2087 fix: inline chain validation
  packages/utils/src/validators.ts
  packages/utils/test/validators.spec.ts
Labels: type: bug, accepted

#2085 fix: removes setting `this.initialized = false`
  packages/core/src/controllers/subscriber.ts
Labels: type: bug, accepted

#2086 Update web3modal version, tag 2.4.8
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#2064 chore(tests): avoids noisy debug logs in test runs
  packages/sign-client/test/shared/values.ts
  packages/web3wallet/test/shared/values.ts
Labels: accepted

#2089 refactor: reimplements pairing checks
  packages/core/src/controllers/pairing.ts
  packages/core/test/pairing.spec.ts
  packages/utils/src/uri.ts
  packages/utils/test/uri.spec.ts
Labels: accepted

#2096 feat(relayer): surface abnormal websocket close reasons
  package-lock.json
  packages/core/package.json
  packages/core/src/controllers/relayer.ts
  packages/sign-client/package.json
  packages/types/src/core/relayer.ts
  packages/utils/src/misc.ts
  packages/utils/test/misc.spec.ts
Labels: accepted

#2098 chore: 2.4.10
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#2103 chore: web3wallet 1.5.0 release
  package-lock.json
  packages/web3wallet/package.json
Labels: accepted

#2105 Make web3modal a peerDependency, expose theming options
  package-lock.json
  providers/ethereum-provider/README.md
  providers/ethereum-provider/package.json
  providers/ethereum-provider/src/EthereumProvider.ts
  providers/ethereum-provider/test/index.spec.ts
Labels: accepted

#2106 ethereum-provider 2.5.0
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  providers/ethereum-provider/README.md
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#2112 fix: @web3modal/standalone not treated as external package
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  providers/ethereum-provider/package.json
  providers/ethereum-provider/rollup.config.js
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#2114 chore(readme): update stale monorepo instructions
  README.md
Labels: accepted

#2131 feat: adds `id` to session_request_sent event params
  packages/sign-client/src/controllers/engine.ts
  packages/types/src/sign-client/client.ts
Labels: accepted

#2132 Web3modal related features & fixes
  package-lock.json
  providers/ethereum-provider/README.md
  providers/ethereum-provider/package.json
  providers/ethereum-provider/src/EthereumProvider.ts
  providers/universal-provider/src/types/misc.ts
  providers/universal-provider/src/utils/deepLinks.ts
Labels: accepted

#2108 fix: connection recovery
  package-lock.json
  package.json
  packages/core/package.json
  packages/core/src/controllers/publisher.ts
  packages/core/src/controllers/relayer.ts
  packages/core/src/controllers/subscriber.ts
  packages/core/test/publisher.spec.ts
  packages/core/test/relayer.spec.ts
  packages/sign-client/package.json
  packages/sign-client/test/lifecycle/lifecycle.spec.ts
  packages/sign-client/test/sdk/integration/events.spec.ts
  packages/sign-client/test/sdk/integration/integration.spec.ts
  packages/sign-client/test/sdk/integration/push.spec.ts
  packages/sign-client/test/shared/init.ts
  packages/sign-client/test/shared/values.ts
  packages/sign-client/test/xregion/xregion.spec.ts
  packages/types/src/core/relayer.ts
  packages/utils/src/misc.ts
Labels: accepted

#2134 fix: catches correctly `socket stalled` rejection
  packages/core/src/controllers/relayer.ts
Labels: accepted

#2135 fix: clients init retry
  packages/sign-client/test/shared/init.ts
Labels: accepted

#2140 fix: get pending requests
  packages/core/src/controllers/store.ts
  packages/core/test/store.spec.ts
  packages/sign-client/src/controllers/pendingRequest.ts
Labels: accepted

#2138 chore(w3w): update auth-client to latest, other @walletconnect/* deps
  package-lock.json
  packages/web3wallet/package.json
Labels: accepted

#2137 feat: caip25 provider handling
  providers/universal-provider/src/UniversalProvider.ts
  providers/universal-provider/src/providers/cardano.ts
  providers/universal-provider/src/providers/cosmos.ts
  providers/universal-provider/src/providers/eip155.ts
  providers/universal-provider/src/providers/elrond.ts
  providers/universal-provider/src/providers/multiversx.ts
  providers/universal-provider/src/providers/solana.ts
  providers/universal-provider/src/utils/misc.ts
  providers/universal-provider/test/index.spec.ts
  providers/universal-provider/test/shared/constants.ts
Labels: type: enhancement, accepted

#2161 feat: auto namespaces
  packages/utils/src/misc.ts
  packages/utils/src/namespaces.ts
  packages/utils/test/validators.spec.ts
Labels: accepted
