Repository WalletConnect/walletconnect-monorepo, pull requests merged in 2023-06, with the labels that each got.

#2523 fix(canary): failures not reported
  packages/sign-client/test/canary/canary.spec.ts
Labels: accepted

#2513 fix: relayer subscribe
  packages/core/src/controllers/relayer.ts
  packages/core/test/relayer.spec.ts
Labels: type: bug

#2532 fix: avoid starting new connection if one is already being started
  packages/core/src/controllers/relayer.ts
Labels: accepted

#2549 Add sideEffects field to ethereum-provider
  providers/ethereum-provider/package.json
Labels: accepted

#2550 chore: prep for `2.7.8` release
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/web3wallet/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#2182 fix(engine): handle payload that is not identifiable request/response
  packages/sign-client/src/controllers/engine.ts
  packages/types/src/sign-client/engine.ts
Labels: accepted

#2560 Add "check/update lockfile" step to Dockerfile
  packages/sign-client/Dockerfile
Labels: accepted

#2562 fix: package-lock.json
  .github/workflows/pr_checks.yml
  package-lock.json
  packages/sign-client/Dockerfile
Labels: accepted

#2563 feat:Expose client id in storage
  packages/core/src/constants/store.ts
  packages/core/src/core.ts
  packages/sign-client/src/constants/client.ts
  packages/sign-client/src/controllers/engine.ts
Labels: accepted

#2569 Update to @walletconnect/modal
  package-lock.json
  providers/ethereum-provider/README.md
  providers/ethereum-provider/package.json
  providers/ethereum-provider/rollup.config.js
  providers/ethereum-provider/src/EthereumProvider.ts
Labels: accepted

#2571 fix: disconnect exceptions
  packages/sign-client/src/controllers/engine.ts
  packages/sign-client/test/sdk/client.spec.ts
  packages/types/src/sign-client/engine.ts
Labels: accepted

#2635 fix(ethereum-provider): removes non-signer/non-wallet optionalMethods
  providers/ethereum-provider/src/constants/rpc.ts
Labels: accepted

#2648 chore: prep for `2.8.1` release
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#2678 chore: web3wallet@1.8.1
  package-lock.json
  packages/web3wallet/package.json
Labels: accepted

#2684 fix: `pairingTopic undefined`
  packages/sign-client/src/controllers/engine.ts
Labels: type: bug, accepted

#2647 remove deprecated eip1193-provider dependency
  package-lock.json
  providers/universal-provider/package.json
  providers/universal-provider/src/UniversalProvider.ts
  providers/universal-provider/src/types/misc.ts
  providers/universal-provider/src/types/providers.ts
Labels: accepted

#2706 fix: ethereum provider persisted session with inline chain declaration
  providers/ethereum-provider/src/EthereumProvider.ts
  providers/ethereum-provider/test/index.spec.ts
Labels: type: bug, type: enhancement, accepted

#2719 refactor: verify - silent POST to loading iframe
  packages/core/src/controllers/verify.ts
Labels: accepted

#2644 chore(relayer): clarify error message for `rejectTransportOpen`
  packages/core/src/controllers/relayer.ts
Labels: accepted

#2724 fix(react-native): detect RN OS via `global.Platform` binding
  packages/react-native-compat/index.js
  packages/utils/src/misc.ts
Labels: accepted

#2679 fix: reconnection on stalled payload
  packages/core/src/controllers/publisher.ts
Labels: type: bug, accepted

#2741 chore: prep for `2.8.2` release
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/web3wallet/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#2765 fix: Remove invalid modal options
  providers/ethereum-provider/src/EthereumProvider.ts
Labels: accepted

#2769 Release 2.8.3
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/web3wallet/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#2792 feat: `wallet_switchEthereumChain` handling if supported by the wallet
  providers/universal-provider/src/providers/eip155.ts
  providers/universal-provider/test/index.spec.ts
  providers/universal-provider/test/shared/WalletClient.ts
  providers/universal-provider/test/shared/constants.ts
Labels: type: enhancement, accepted

#2798 chore: prep for `2.8.4` release
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/web3wallet/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#2808 fix: namespace chains validation
  packages/sign-client/test/sdk/validation.spec.ts
  packages/utils/src/validators.ts
  packages/utils/test/validators.spec.ts
Labels: type: bug, accepted

#2827 fix: `accountsChanged` CAIP-10 accounts in `universal-provider`
  providers/universal-provider/src/UniversalProvider.ts
  providers/universal-provider/src/utils/misc.ts
  providers/universal-provider/test/index.spec.ts
Labels: type: bug, accepted

#2847 chore: prep for `2.8.5` release
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/web3wallet/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#2864 feat(relayer): implements failover logic to `relay.org`
  packages/core/src/constants/relayer.ts
  packages/core/src/controllers/relayer.ts
  packages/core/test/relayer.spec.ts
  packages/core/test/shared/ws.ts
Labels: accepted

#2869 Open request http redirects in a new tab
  packages/utils/src/misc.ts
Labels: accepted

#2871 Release 2.8.6
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/web3wallet/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#2899 fix: switch chain
  providers/universal-provider/src/providers/eip155.ts
  providers/universal-provider/test/index.spec.ts
Labels: type: bug, accepted
