Repository WalletConnect/walletconnect-monorepo, pull requests merged in 2023-01, with the labels that each got.

#1826 fix: validate set default chain
  providers/universal-provider/src/UniversalProvider.ts
  providers/universal-provider/test/index.spec.ts
Labels: type: bug, type: enhancement, accepted

#1832 feat: empty required namespaces
  packages/sign-client/src/controllers/engine.ts
  packages/sign-client/test/sdk/client.spec.ts
  packages/sign-client/test/sdk/validation.spec.ts
  packages/types/src/sign-client/engine.ts
  packages/types/src/sign-client/jsonrpc.ts
  packages/utils/src/namespaces.ts
Labels: accepted

#1834 feat: pending pairigs cleanup
  providers/universal-provider/package.json
  providers/universal-provider/src/UniversalProvider.ts
  providers/universal-provider/src/types/providers.ts
  providers/universal-provider/test/index.spec.ts
Labels: type: enhancement

#1836 2.2.0
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#1838 fix(scripts): differentiate `sed` command by platform
  scripts/update_relayer_sdk_version.sh
Labels: accepted

#1839 fix: check if relay event is related to a pairing topic
  packages/core/src/controllers/pairing.ts
Labels: accepted

#1843 fix: expirer pending requests
  packages/core/src/controllers/expirer.ts
  packages/core/test/expirer.spec.ts
  packages/sign-client/src/controllers/engine.ts
Labels: type: bug

#1851 feat: optional request expiry
  packages/core/src/constants/relayer.ts
  packages/core/src/controllers/publisher.ts
  packages/sign-client/src/constants/engine.ts
  packages/sign-client/src/controllers/engine.ts
  packages/sign-client/test/sdk/client.spec.ts
  packages/sign-client/test/sdk/validation.spec.ts
  packages/types/src/core/relayer.ts
  packages/types/src/sign-client/engine.ts
  packages/utils/src/misc.ts
  packages/utils/src/validators.ts
Labels: type: enhancement, accepted

#1852 feat: subscriptions clean up
  providers/universal-provider/src/UniversalProvider.ts
  providers/universal-provider/src/types/providers.ts
  providers/universal-provider/test/index.spec.ts
Labels: type: enhancement, accepted

#1858 Tag 2.2.1
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/web3wallet/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#1863 chore: web3wallet deps bump
  package-lock.json
  packages/web3wallet/package.json
Labels: accepted

#1865 feat: web3wallet readme
  packages/web3wallet/README.md
Labels: scope: docs, accepted

#1868 chore(templates): adds sub-section for link to docs issue/PR
  .github/pull_request_template.md
Labels: accepted

#1869 chore: bumped heartbeat
  package-lock.json
  packages/core/package.json
  packages/sign-client/package.json
  packages/sign-client/test/shared/helpers.ts
  packages/types/package.json
  providers/universal-provider/test/shared/ws.ts
Labels: type: dependencies, accepted

#1874 refactor: session extension
  packages/sign-client/test/sdk/validation.spec.ts
  packages/types/src/sign-client/proposal.ts
  packages/types/src/sign-client/session.ts
  packages/utils/src/namespaces.ts
  packages/utils/src/validators.ts
  providers/ethereum-provider/test/shared/WalletClient.ts
  providers/universal-provider/test/shared/WalletClient.ts
Labels: accepted

#1890 chore: bumped web3wallet dependencies
  package-lock.json
  packages/web3wallet/package.json
Labels: type: dependencies, accepted

#1882 feat: ethereum provider
  .github/workflows/pr_checks.yml
  package-lock.json
  package.json
  packages/core/src/controllers/relayer.ts
  packages/sign-client/package.json
  packages/web3wallet/package.json
  providers/ethereum-provider/README.md
  providers/ethereum-provider/package.json
  providers/ethereum-provider/rollup.config.js
  providers/ethereum-provider/src/EthereumProvider.ts
  providers/ethereum-provider/src/index.ts
  providers/ethereum-provider/test/index.spec.ts
  providers/ethereum-provider/test/shared/WalletClient.ts
  providers/ethereum-provider/test/shared/constants.ts
  providers/universal-provider/src/UniversalProvider.ts
  providers/universal-provider/src/types/misc.ts
  providers/universal-provider/test/index.spec.ts
  rollup.config.js
Labels: type: enhancement, accepted

#1894 fix(template): tweaks new-chains template w/ additional required data
  .github/ISSUE_TEMPLATE/new_chain_to_explorer.md
Labels: accepted

#1895 refactor: disconnect pairings in universal-provider
  providers/universal-provider/src/UniversalProvider.ts
  providers/universal-provider/src/types/providers.ts
  providers/universal-provider/test/index.spec.ts
  providers/universal-provider/test/shared/connect.ts
Labels: type: enhancement, accepted

#1896 chore: 2.3.1
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#1898 fix(engine): adds missing emit for `proposal_expire`
  packages/sign-client/src/controllers/engine.ts
Labels: accepted

#1901 refactor: provider full cleanup on disconnect
  packages/sign-client/src/controllers/engine.ts
  providers/universal-provider/src/UniversalProvider.ts
  providers/universal-provider/src/types/misc.ts
  providers/universal-provider/test/index.spec.ts
Labels: type: enhancement, accepted

#1902 fix: websocket cleanup in tests
  packages/sign-client/test/sdk/integration/integration.spec.ts
  packages/sign-client/test/sdk/integration/push.spec.ts
  packages/sign-client/test/shared/helpers.ts
Labels: accepted

#1903 chore: 2.3.2
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/web3wallet/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#1911 refactor: ethereum provider
  providers/ethereum-provider/src/EthereumProvider.ts
  providers/ethereum-provider/test/index.spec.ts
  providers/ethereum-provider/test/shared/WalletClient.ts
Labels: type: enhancement, accepted

#1912 feat: web3wallet session_delete
  packages/web3wallet/README.md
  packages/web3wallet/src/controllers/engine.ts
  packages/web3wallet/src/types/client.ts
  packages/web3wallet/test/sign.spec.ts
Labels: type: enhancement, accepted
