Repository WalletConnect/walletconnect-monorepo, pull requests merged in 2023-02, with the labels that each got.

#1922 Fix/w3m universal provider
  providers/universal-provider/src/UniversalProvider.ts
Labels: accepted

#1923 2.3.3
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#1934 fix: avoids restarting transport if explicitly closed
  packages/core/src/controllers/relayer.ts
Labels: accepted

#1933 fix(providers): incomplete context comment in readme
  providers/ethereum-provider/README.md
Labels: accepted

#1932 Add deeplink redirects for rpc requests
  providers/universal-provider/package.json
  providers/universal-provider/src/providers/cardano.ts
  providers/universal-provider/src/providers/cosmos.ts
  providers/universal-provider/src/providers/eip155.ts
  providers/universal-provider/src/providers/solana.ts
  providers/universal-provider/src/utils/misc.ts
Labels: accepted

#1937 chore: updating deps
  package-lock.json
  packages/core/package.json
  packages/core/src/controllers/subscriber.ts
  packages/sign-client/package.json
  packages/sign-client/test/shared/helpers.ts
  packages/web3wallet/package.json
  providers/ethereum-provider/package.json
  providers/ethereum-provider/src/EthereumProvider.ts
Labels: type: dependencies, accepted

#1940 fix: subscriber not initialized
  packages/core/src/controllers/subscriber.ts
  packages/core/test/subscriber.spec.ts
  providers/ethereum-provider/test/index.spec.ts
  providers/universal-provider/test/index.spec.ts
Labels: accepted

#1942 fix(utils): ensures matching units in `isExpired`, adds tests for expiry calcs
  packages/utils/src/misc.ts
  packages/utils/test/misc.spec.ts
Labels: accepted

#1944 refactor: requests order
  packages/sign-client/src/controllers/engine.ts
Labels: accepted

#1926 feat: caip-25
  packages/sign-client/src/controllers/engine.ts
  packages/sign-client/test/sdk/client.spec.ts
  packages/sign-client/test/sdk/validation.spec.ts
  packages/sign-client/test/shared/connect.ts
  packages/sign-client/test/shared/values.ts
  packages/types/src/sign-client/engine.ts
  packages/types/src/sign-client/jsonrpc.ts
  packages/types/src/sign-client/proposal.ts
  packages/types/src/sign-client/session.ts
  packages/utils/src/caip.ts
  packages/utils/src/validators.ts
  providers/ethereum-provider/test/index.spec.ts
  providers/universal-provider/test/index.spec.ts
Labels: type: enhancement, accepted

#1947 chore: 2.4.0
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: type: dependencies, accepted

#1951 fix(core): ensures `core.relayUrl` property is assigned
  packages/core/src/core.ts
Labels: accepted

#1962 fix: avoid expirer events when connection is down
  packages/core/src/controllers/expirer.ts
Labels: type: bug, accepted

#1966 feat: session request sent
  packages/sign-client/src/constants/client.ts
  packages/sign-client/src/controllers/engine.ts
  packages/types/src/sign-client/client.ts
  providers/universal-provider/src/providers/cardano.ts
  providers/universal-provider/src/providers/cosmos.ts
  providers/universal-provider/src/providers/eip155.ts
  providers/universal-provider/src/providers/solana.ts
  providers/universal-provider/src/utils/deepLinks.ts
  providers/universal-provider/src/utils/index.ts
  providers/universal-provider/src/utils/misc.ts
Labels: type: enhancement, accepted

#1956 feat: optional namespaces in providers
  package-lock.json
  providers/ethereum-provider/src/EthereumProvider.ts
  providers/ethereum-provider/src/constants/index.ts
  providers/ethereum-provider/src/constants/values.ts
  providers/ethereum-provider/test/index.spec.ts
  providers/ethereum-provider/test/shared/WalletClient.ts
  providers/ethereum-provider/test/shared/constants.ts
  providers/universal-provider/src/UniversalProvider.ts
  providers/universal-provider/src/types/misc.ts
  providers/universal-provider/test/index.spec.ts
Labels: type: enhancement, accepted

#1974 chore: 2.4.1
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#1977 Release 2.4.2, dynamic import for web3modal
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  providers/ethereum-provider/package.json
  providers/ethereum-provider/src/EthereumProvider.ts
  providers/ethereum-provider/test/index.spec.ts
  providers/ethereum-provider/test/shared/WalletClient.ts
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#1982 fix: unsubscribe `transport_closed` listener
  packages/core/src/controllers/relayer.ts
Labels: accepted

#1986 fix: persist optional chains
  providers/universal-provider/src/UniversalProvider.ts
  providers/universal-provider/test/index.spec.ts
  providers/universal-provider/test/shared/WalletClient.ts
  providers/universal-provider/test/shared/connect.ts
  providers/universal-provider/test/shared/constants.ts
Labels: type: bug, type: enhancement, accepted

#1985 export method and event constants, types
  providers/ethereum-provider/src/EthereumProvider.ts
  providers/ethereum-provider/src/constants/index.ts
  providers/ethereum-provider/src/constants/rpc.ts
  providers/ethereum-provider/src/constants/values.ts
  providers/ethereum-provider/src/index.ts
Labels: accepted

#1987 feat: Added `pair` method in web3wallet
  package-lock.json
  packages/web3wallet/package.json
  packages/web3wallet/src/client.ts
  packages/web3wallet/src/controllers/engine.ts
  packages/web3wallet/src/types/client.ts
  packages/web3wallet/src/types/engine.ts
  packages/web3wallet/test/auth.spec.ts
  packages/web3wallet/test/sign.spec.ts
Labels: type: enhancement, accepted

#1990 chore: 2.4.3
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/web3wallet/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: type: dependencies, accepted

#1992 chore: web3wallet release `1.2.0`
  package-lock.json
  packages/web3wallet/package.json
Labels: accepted

#1999 refactor: active chains persitence
  providers/ethereum-provider/src/EthereumProvider.ts
  providers/universal-provider/src/UniversalProvider.ts
  providers/universal-provider/src/constants/events.ts
  providers/universal-provider/src/constants/index.ts
  providers/universal-provider/src/providers/cardano.ts
  providers/universal-provider/src/providers/cosmos.ts
  providers/universal-provider/src/providers/eip155.ts
  providers/universal-provider/src/providers/solana.ts
  providers/universal-provider/src/types/misc.ts
  providers/universal-provider/src/types/providers.ts
  providers/universal-provider/src/utils/misc.ts
  providers/universal-provider/test/index.spec.ts
Labels: type: bug, type: enhancement, accepted

#1950 Remove eip1193-provider dependency
  providers/ethereum-provider/package.json
  providers/ethereum-provider/src/EthereumProvider.ts
  providers/ethereum-provider/src/types.ts
Labels: accepted

#2000 chore: 2.4.4
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/web3wallet/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: type: dependencies, accepted

#2011 refactor: chainChanged in hex
  providers/ethereum-provider/src/EthereumProvider.ts
  providers/ethereum-provider/src/types.ts
  providers/ethereum-provider/test/index.spec.ts
Labels: type: enhancement, accepted

#2013 fix: removes pairing delete response
  packages/core/src/controllers/pairing.ts
Labels: accepted

#2025 chore(deps): update web3wallet to auth-client@2.0.3
  package-lock.json
  packages/web3wallet/package.json
  packages/web3wallet/test/auth.spec.ts
Labels: accepted

#2020 fix: connection rejection
  providers/ethereum-provider/src/EthereumProvider.ts
  providers/universal-provider/src/constants/values.ts
  providers/universal-provider/src/providers/cardano.ts
  providers/universal-provider/src/providers/cosmos.ts
  providers/universal-provider/src/providers/eip155.ts
  providers/universal-provider/src/providers/solana.ts
  providers/universal-provider/src/utils/misc.ts
Labels: type: bug, accepted

#2026 chore: `2.4.5`
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/web3wallet/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#2030 fix: `ProviderRpcError` type to extend `Error`
  providers/ethereum-provider/src/EthereumProvider.ts
  providers/ethereum-provider/src/types.ts
Labels: type: bug

#2032 feat: `irn_batchSubscribe`
  package-lock.json
  packages/core/package.json
  packages/core/src/controllers/subscriber.ts
  packages/sign-client/package.json
  packages/utils/package.json
Labels: accepted

#2036 feat(core): emit publishedAt as part of relayer MessageEvent
  package-lock.json
  packages/core/package.json
  packages/core/src/controllers/relayer.ts
  packages/core/test/relayer.spec.ts
  packages/sign-client/package.json
  packages/types/src/core/relayer.ts
  packages/utils/package.json
Labels: accepted

#2037 feat: pending proposal expiry
  packages/sign-client/src/constants/proposal.ts
  packages/sign-client/src/controllers/engine.ts
  packages/utils/src/misc.ts
  providers/ethereum-provider/src/EthereumProvider.ts
  providers/universal-provider/src/UniversalProvider.ts
  providers/universal-provider/src/types/providers.ts
Labels: type: bug, type: enhancement

#2038 chore: release `2.4.6`
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/web3wallet/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: type: dependencies, accepted

#2049 fix: validate pairing uri
  packages/core/test/pairing.spec.ts
  packages/utils/src/uri.ts
  packages/utils/test/uri.spec.ts
Labels: type: bug, accepted

#2050 fix: ethereum-provider `on` return type
  providers/ethereum-provider/src/EthereumProvider.ts
  providers/ethereum-provider/src/types.ts
Labels: accepted
