Repository WalletConnect/walletconnect-monorepo, pull requests merged in 2023-04, with the labels that each got.

#2172 chore: 2.6.0
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#2176 fix: dedicated session ack tests
  packages/sign-client/test/sdk/client.spec.ts
  packages/sign-client/test/shared/connect.ts
Labels: accepted

#2177 refactor: auto-namespaces to accept session proposal
  packages/utils/src/namespaces.ts
  packages/utils/test/validators.spec.ts
Labels: type: enhancement, accepted

#2178 chore: bump dependencies
  package-lock.json
  packages/core/package.json
  packages/sign-client/package.json
  packages/utils/package.json
  packages/web3wallet/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: type: dependencies

#2179 chore: prep for `2.6.1` release
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/web3wallet/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: type: dependencies

#2186 chore: rearanged util dependencies
  package-lock.json
  packages/core/package.json
  packages/sign-client/package.json
  packages/web3wallet/package.json
  providers/signer-connection/package.json
Labels: accepted

#2187 chore: prep for `2.6.2` release
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/web3wallet/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: type: dependencies, accepted

#2143 fix: provider persistence with inline chains declaration
  providers/universal-provider/src/UniversalProvider.ts
  providers/universal-provider/src/utils/misc.ts
  providers/universal-provider/test/index.spec.ts
Labels: accepted

#2197 fix: removes session from storage before emitting `session_delete` event
  packages/sign-client/src/controllers/engine.ts
  packages/sign-client/test/sdk/integration/events.spec.ts
Labels: accepted

#2189 re: Chalker/pino from logger
  package-lock.json
  packages/core/package.json
  packages/core/src/controllers/relayer.ts
  packages/core/src/core.ts
  packages/sign-client/package.json
  packages/sign-client/src/client.ts
  providers/universal-provider/package.json
  providers/universal-provider/src/UniversalProvider.ts
Labels: type: dependencies, accepted

#2199 fix: wrapps try-catch around `verify-api`'s resolve fx
  packages/sign-client/src/controllers/engine.ts
Labels: accepted

#2203 fix(ci): don't use auto-promote job on `renovate[bot]`
  .github/workflows/intake.yml
Labels: accepted

#2206 fix(deps): use non-caret explicit version for heartbeat
  packages/sign-client/package.json
Labels: accepted

#2208 fix: transport restart
  packages/core/src/controllers/relayer.ts
  packages/core/src/controllers/subscriber.ts
  packages/core/test/relayer.spec.ts
Labels: type: bug, accepted

#2209 chore: prep for `2.7.0` release
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted

#2211 feat: web3wallet verify api
  package-lock.json
  packages/sign-client/src/controllers/engine.ts
  packages/web3wallet/package.json
  packages/web3wallet/src/types/client.ts
  packages/web3wallet/test/sign.spec.ts
Labels: accepted

#2236 fix: auto namespace builder chains match
  packages/utils/src/namespaces.ts
  packages/utils/test/validators.spec.ts
Labels: type: bug, accepted

#2260 fix: restart connection
  packages/core/src/constants/relayer.ts
  packages/core/src/controllers/relayer.ts
  packages/core/test/relayer.spec.ts
Labels: accepted

#2270 chore: prep for `1.6.0` release
  package-lock.json
  packages/web3wallet/package.json
Labels: accepted

#2273 fix: resolve origin only on 200 response
  packages/core/src/controllers/verify.ts
Labels: accepted

#2275 chore: prep for `2.7.2` release
  lerna.json
  package-lock.json
  packages/core/package.json
  packages/core/src/constants/relayer.ts
  packages/react-native-compat/package.json
  packages/sign-client/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/web3wallet/package.json
  providers/ethereum-provider/package.json
  providers/signer-connection/package.json
  providers/universal-provider/package.json
Labels: accepted
